pudding-tech/mikane

app/mikane/src/app/app-routing.module.ts
app/mikane/src/app/pages/events/events.component.scss
app/mikane/src/app/pages/reset-password/reset-password.component.html
app/mikane/src/app/pages/reset-password/reset-password.component.scss
app/mikane/src/app/pages/reset-password/reset-password.component.ts
app/mikane/src/app/pages/reset-password/reset-password.routes.ts
app/mikane/src/app/pages/settings/change-password/change-password.component.ts
app/mikane/src/app/services/auth/auth.service.ts
app/mikane/src/app/shared/forms/validators/compare.validator.ts
app/mikane/src/styles.scss

implement password reset page

---

app/mikane/src/app/features/menu/menu.component.html
app/mikane/src/app/features/menu/menu.component.scss
app/mikane/src/app/features/menu/menu.component.ts
app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.html
app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.scss
app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.ts
app/mikane/src/app/features/split-button/split-button-item/split-button-item.directive.ts
app/mikane/src/app/features/split-button/split-button.component.html
app/mikane/src/app/features/split-button/split-button.component.scss
app/mikane/src/app/features/split-button/split-button.component.ts
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/register/register-user.component.ts
app/mikane/src/app/pages/settings/settings.component.ts
app/mikane/src/app/pages/settings/user/user-settings.component.ts
app/mikane/src/app/pages/user/expense.datasource.ts
app/mikane/src/app/pages/user/user-dialog/user-dialog.component.ts
app/mikane/src/app/services/event/event.service.ts
app/mikane/src/app/services/expense/expense.service.spec.ts
app/mikane/tsconfig.json

Allows an arbitrary number of menu items with supplied callback, icon and label
Closes #76

make split button a generic component

---

app/mikane/src/app/features/mobile/event-item/event-item.component.html
app/mikane/src/app/features/mobile/event-item/event-item.component.scss
app/mikane/src/app/features/mobile/event-item/event-item.component.ts
app/mikane/src/app/features/mobile/expense-item/expense-item.component.scss
app/mikane/src/app/pages/events/event/event.component.html
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/events/events.component.html
app/mikane/src/app/pages/events/events.component.scss
app/mikane/src/app/pages/events/events.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.scss
app/mikane/src/styles.scss

Adds a mobile friendly UI for the main events page.
Closes #132

Mobile layout - events

---

server/db_scripts/db_init.sh
server/src/server.ts

Changelog:
- Implement error handler for invalid JSON in body
- Improve bash script for initializing database
Closes #150

Error handler for invalid JSON in body

---

.vscode/settings.json
app/mikane/angular.json
app/mikane/src/app/pages/events/event/event.component.html
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.scss
app/mikane/src/app/pages/expenditures/expenditures.component.ts

add admin check for expense delete button

---

app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.html
app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.ts
app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/category/category.component.ts

open category with current weight and only allow numbers

---

app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.ts

also allow payer to change when creating expense from pariticpant page
Closes #75

preselect current user as payer when creating new expense

---

app/mikane/src/app/pages/events/event-dialog/event-dialog.component.html
app/mikane/src/app/pages/events/events.component.ts

also fixed issue where edited event did not show up without refresh
Closes #61
Closes #62

prevent user from submitting invalid event and made description optional

---

app/mikane/src/app/pages/category/category.component.ts

display correct weights when toggling category weighted

---

app/mikane/src/app/features/footer/footer.component.ts
app/mikane/src/app/features/mobile/mobile-navbar/mobile-navbar.component.ts
app/mikane/src/app/pages/events/event/event.component.html
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/login/login.component.html
app/mikane/src/app/pages/login/login.component.scss
app/mikane/src/app/pages/login/login.component.ts

Changelog:
- Implement mobile app styling for login page
- Refactor mobile navbar to use links object passed from event component
Closes #137

Mobile layout - login

---

app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/category/category.component.ts
app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
app/mikane/src/app/shared/forms/validators/form-control.pipe.ts

use material select when not on mobile

---

app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.html
app/mikane/src/app/pages/category/category-edit-dialog/category-edit-dialog.component.ts
app/mikane/src/app/pages/category/category.component.ts

Added validation message for weight edit dialog, but message doesn't fit when adding in table view, so not using it there for now
Closes #14

add min validation for category user weight

---

app/mikane/src/app/pages/register/register-user.component.html
app/mikane/src/app/pages/register/register-user.component.ts

add validation feedback when registering user based on backend response

---

app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.scss
app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
app/mikane/src/app/pages/events/event/event.component.html
app/mikane/src/app/pages/events/event/event.component.scss
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.scss
app/mikane/src/app/pages/expenditures/expenditures.component.ts
app/mikane/src/app/services/context/context.service.ts

Implements a check for iOS devices, as well as some specific styling of the event navbar when using a iOS device.
Closes #192

iOS specific styling

---

.gitattributes
server/db_scripts/get_expenses.sql
server/db_scripts/new_expense.sql
server/db_scripts/remove_user_from_event.sql
server/src/api.json
server/src/db/dbEvents.ts
server/src/db/dbUsers.ts
server/src/parsers/parseExpenses.ts
server/src/parsers/parseUsers.ts
server/src/types/errorCodes.ts
server/src/types/typesDB.ts
server/tests/events.test.ts

Changelog:
- Fix issue where the last event admin could be removed from an event
- Add the payers avatarURL when getting expenses
- Add gitattributes file to fix Linux/Windows specific line endings
- Support for dynamic avatar sizes when calling certain user functions
- Fix bug with incorrect admin status when parsing users
- Add test for removing last event admin from an event
- Add test for setting the last event admin as non-admin
Closes #196

Various backend improvements

---

app/mikane/src/app/features/mobile/expense-item/expense-item.component.html
app/mikane/src/app/features/mobile/expense-item/expense-item.component.scss
app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.scss
app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
app/mikane/src/app/features/mobile/participant-item/participant-item.component.html
app/mikane/src/app/features/mobile/participant-item/participant-item.component.scss
app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.scss
app/mikane/src/app/pages/user/user.component.html
app/mikane/src/app/pages/user/user.component.scss
app/mikane/src/app/pages/user/user.component.ts
app/mikane/src/app/services/user/user.service.ts
app/mikane/src/manifest.webmanifest
app/mikane/src/styles.scss

Changelog:
- Implement mobile app styling for event participants page
- Add back button to mobile event navbar
- Add user avatars to event expenses page (both computer and mobile)
Closes #133

Mobile layout - participants

---

app/mikane/src/app/pages/account/account.component.html
app/mikane/src/app/pages/account/account.component.scss
app/mikane/src/app/pages/account/account.component.ts
app/mikane/src/app/pages/account/danger-zone/danger-zone.component.ts
app/mikane/src/app/pages/account/user/user-settings.component.ts

Also refactored code so user is only fetched on parent account component instead of in child components
Closes #198

show error message on account page if getting user fails

---

app/mikane/src/app/pages/account/user/user-settings.component.ts
app/mikane/src/app/services/user/user.service.ts

fix error that prevented user editing

---

app/mikane/src/app/pages/category/category.component.html

Fixed for mobile and full view
Fixes #186

fix weighted input field vertical alignment

---

app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts

add validation to expense dialog

---

server/db_scripts/invalidate_register_account_key.sql
server/db_scripts/new_register_account_key.sql
server/db_scripts/verify_register_account_key.sql
server/package-lock.json
server/package.json
server/src/api.json
server/src/api/authentication.ts
server/src/api/users.ts
server/src/db/dbUsers.ts
server/src/email-services/registerAccount.ts
server/src/env.ts
server/src/types/errorCodes.ts
server/test.env
server/tests/authentication.test.ts
server/tests/users.test.ts
server/vitest.config.ts

Implements functionality for inviting users through sending invitation emails.
Changelog:
- Endpoint for inviting user (send invitation email)
- Endpoint for verifying if a register account key is valid
- Change POST /users endpoint to require a register account key when running in production
- Add support for testing email related endpoints
- Update API documentation
Closes #47

Invite users via email

---

app/mikane/src/app/app-routing.module.ts
app/mikane/src/app/app.component.ts
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/events/events.routes.ts
app/mikane/src/app/pages/invite/invite.component.html
app/mikane/src/app/pages/invite/invite.component.ts
app/mikane/src/app/pages/login/login.component.ts
app/mikane/src/app/services/auth/auth.guard.spec.ts
app/mikane/src/app/services/auth/auth.guard.ts
app/mikane/src/app/services/auth/auth.interceptor.ts
app/mikane/src/app/services/auth/auth.service.ts
app/mikane/src/app/services/auth/logged-in.guard.spec.ts
app/mikane/src/app/services/auth/logged-in.guard.ts
app/mikane/src/main.ts

* Added guard for preventing unauthorized access and guard for preventing authorized access to login, reset password and register pages
* Added redirecting after login to page user tried to open
* If trying to open URL to an event that does not exist, redirect to event list
Closes #64

feat: add auth guards to prevent access

---

app/mikane/src/app/app-routing.module.ts
app/mikane/src/app/pages/account/danger-zone/danger-zone.component.html
app/mikane/src/app/pages/account/danger-zone/danger-zone.component.ts
app/mikane/src/app/pages/delete-account/delete-account.component.html
app/mikane/src/app/pages/delete-account/delete-account.component.scss
app/mikane/src/app/pages/delete-account/delete-account.component.ts
app/mikane/src/app/pages/delete-account/delete-account.routes.ts
app/mikane/src/app/pages/register/register-user.component.html
app/mikane/src/app/pages/register/register-user.component.ts
app/mikane/src/app/pages/register/register-user.routes.ts
app/mikane/src/app/pages/reset-password/reset-password.component.ts
app/mikane/src/app/services/auth/auth.service.ts
app/mikane/src/app/services/key-validation/key-validation.service.ts
app/mikane/src/app/services/user/user.service.ts

* User deletion on account page now requests account deletion email
* Link in email contains key required to view delete account page
* Separated key validation endpoints to separate service
Closes #214

feat: implement delete account page

---

server/db_scripts/verify_register_account_key.sql
server/src/api.json
server/src/api/categories.ts
server/src/api/events.ts
server/src/api/users.ts
server/src/api/validation.ts
server/src/db/dbUsers.ts
server/src/db/dbValidation.ts
server/src/email-services/deleteAccount.ts
server/src/server.ts
server/src/types/errorCodes.ts
server/src/utils/phoneValidator.ts
server/tests/users.test.ts
server/tests/validation.test.ts

- Implement endpoints for several input validations
- Register account:
- Create event:
- Add category:
- Return email associated with verified register account key
- Update API documentation
- Tests for new endpoints
Closes #212

feat: Backend validation endpoints

---

app/mikane/karma.conf.js
app/mikane/src/app/pages/category/category.component.spec.ts
app/mikane/src/app/pages/events/events.component.spec.ts
app/mikane/src/app/pages/expenditures/expenditures.component.spec.ts
app/mikane/src/app/pages/participant/participant.component.spec.ts
app/mikane/src/app/pages/payment-structure/payment-structure.component.spec.ts
app/mikane/src/app/pages/register/register-user.component.ts
app/mikane/src/app/pages/register/register-user.routes.ts
app/mikane/src/app/services/auth/auth.service.spec.ts
app/mikane/src/app/services/auth/auth.service.ts
app/mikane/src/app/services/breakpoint/breakpoint.service.spec.ts
app/mikane/src/app/services/category/category.service.spec.ts
app/mikane/src/app/services/category/category.service.ts
app/mikane/src/app/services/context/context.service.spec.ts
app/mikane/src/app/services/context/context.service.ts
app/mikane/src/app/services/event/event.service.spec.ts
app/mikane/src/app/services/event/event.service.ts
app/mikane/src/app/services/expense/expense.service.spec.ts
app/mikane/src/app/services/expense/expense.service.ts
app/mikane/src/app/services/key-validation/key-validation.service.spec.ts
app/mikane/src/app/services/key-validation/key-validation.service.ts
app/mikane/src/app/services/user/user.service.spec.ts
app/mikane/src/app/services/user/user.service.ts
app/mikane/src/environments/environment.interface.ts
app/mikane/src/environments/environment.prod.ts
app/mikane/src/environments/environment.provider.ts
app/mikane/src/environments/environment.ts
app/mikane/src/main.ts

Also changed environment to an injection token so it has type safety and can be mocked in tests

Frontend testing

---

app/mikane/src/app/features/menu/menu.component.html
app/mikane/src/app/features/menu/menu.component.ts
app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.html
app/mikane/src/app/features/split-button/split-button-item/split-button-item.component.ts
app/mikane/src/app/features/split-button/split-button.component.html
app/mikane/src/app/features/split-button/split-button.component.ts

refactor: use output and event emitter for split button actions

---

app/mikane/src/app/features/mobile/category-item/category-item.component.html
app/mikane/src/app/features/mobile/category-item/category-item.component.scss
app/mikane/src/app/features/mobile/category-item/category-item.component.ts
app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/category/category.component.scss
app/mikane/src/app/pages/category/category.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.ts
app/mikane/src/app/pages/participant/participant.component.ts
app/mikane/src/app/services/category/category.service.ts

Implements mobile app styling for event categories page.
Closes #135

Mobile layout - categories

---

app/mikane/src/app/features/mobile/category-item/category-item.component.scss
app/mikane/src/app/pages/invite/invite.component.html
app/mikane/src/app/pages/invite/invite.component.scss

Implements mobile app styling for the invite page.
Closes #227

feat: Mobile layout - invite

---

app/mikane/src/app/pages/delete-account/delete-account.component.html
app/mikane/src/app/pages/delete-account/delete-account.component.scss

Implements mobile app styling for the delete account page.
Closes #228

feat: Mobile layout - delete account

---

app/mikane/src/app/features/mobile/category-item/category-item.component.ts
app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
app/mikane/src/app/features/mobile/payment-item/payment-item.component.scss
app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/payment-structure/payment-structure.component.html
app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
app/mikane/src/app/pages/payment-structure/payment-structure.component.ts

Implements mobile app styling for the event payments page.
Closes #136
Closes #5

feat: Mobile layout - payments

---

app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/category/category.component.scss

Changelog:
- Disable add user to category input when all users are in category
- Add number of participants to the categories page
Closes #170

feat: Improve categories page

---

app/mikane/src/app/features/mobile/category-item/category-item.component.html
app/mikane/src/app/features/mobile/category-item/category-item.component.ts
app/mikane/src/app/pages/category/category-dialog/category-dialog.component.html
app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/category/category.component.ts
app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.ts
app/mikane/src/app/services/category/category.service.ts
app/mikane/src/app/services/expense/expense.service.ts

feat: implement category and expense editing

---

app/mikane/src/app/pages/expenditures/expenditures.component.ts
app/mikane/src/app/pages/participant/participant.component.html
app/mikane/src/app/pages/participant/participant.component.ts

feat: add sorting to participant list

---

app/mikane/src/app/pages/participant/participant.component.ts
app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.html
app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.ts

Added improvements to adding user to event dialog
- Use autocomplete for user list
- Use chips or currently selected users
Closes #247

feat: add user improvements

---

app/mikane/src/app/pages/events/events.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.ts

- sets query param 'filter'
- entering with query param applies filter
- layout changes clears filter input
Closes #246

feat: add filter to expense table

---

app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
app/mikane/src/app/pages/events/event/event.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.ts

fix: nav bar link not active when expense filtered

---

app/mikane/src/app/features/mobile/category-item/category-item.component.html
app/mikane/src/app/features/mobile/category-item/category-item.component.ts
app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/category/category.component.ts
app/mikane/src/app/pages/event-settings/event-settings.component.ts
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.ts
app/mikane/src/app/pages/participant/participant.component.html
app/mikane/src/app/pages/participant/participant.component.ts

feat: hide buttons and actions when event is archived

---

server/src/parsers/parseCategories.ts
server/src/parsers/parseExpenses.ts
server/src/parsers/parseUsers.ts
server/src/types/types.ts

Separates avatars for users and guests. Now guests will have the mystery person avatar, while users (without a custom gravatar) will get a geometric pattern based on their email hash.

feat: Different avatars for users and guests

---

app/mikane/src/app/app-routing.module.ts
app/mikane/src/app/features/menu/menu.component.html
app/mikane/src/app/features/menu/menu.component.ts
app/mikane/src/app/pages/account/change-password/change-password.component.scss
app/mikane/src/app/pages/account/danger-zone/danger-zone.component.html
app/mikane/src/app/pages/account/danger-zone/danger-zone.component.scss
app/mikane/src/app/pages/account/user/user-settings.component.scss
app/mikane/src/app/pages/event-settings/event-settings.component.html
app/mikane/src/app/pages/event-settings/event-settings.component.ts
app/mikane/src/app/pages/events/event-dialog/event-dialog.component.html
app/mikane/src/app/pages/events/events.component.scss
app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.html
app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.scss
app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.ts
app/mikane/src/app/pages/guests/guests.component.html
app/mikane/src/app/pages/guests/guests.component.scss
app/mikane/src/app/pages/guests/guests.component.ts
app/mikane/src/app/pages/guests/guests.routes.ts
app/mikane/src/app/pages/invite/invite.component.html
app/mikane/src/app/pages/invite/invite.component.ts
app/mikane/src/app/pages/register/register-user.routes.ts
app/mikane/src/app/services/auth/auth.service.spec.ts
app/mikane/src/app/services/user/user.service.ts

Implements a guests page for managing guest users
Notable changes:
- Guests page (full view & mobile) for guest management, including:
- List all guests
- Create new guest
- Edit guest
- Delete guest
- Add new section to invite page for inviting a user from a guest (full view & mobile)
- Modify users service to allow getting users without guests
Closes #279, closes #280

feat: Guest users page

---

app/mikane/src/app/features/menu/menu.component.html
app/mikane/src/app/pages/profile/profile.component.html
app/mikane/src/app/pages/profile/profile.component.scss

Implements mobile app styling for the profile page. Also adds a profile button in the main dropdown when in mobile view.
Closes #283

feat: Mobile layout - Profile

---

app/mikane/src/app/pages/invite/invite.component.html
app/mikane/src/app/pages/invite/invite.component.ts
app/mikane/src/app/pages/register/register-user.component.html
app/mikane/src/app/pages/register/register-user.component.ts
app/mikane/src/app/pages/register/register-user.routes.ts
app/mikane/src/app/services/key-validation/key-validation.service.ts

feat: prefill guest user info when registering a guest user

---

app/mikane/src/app/pages/event-info/event-info.component.html
app/mikane/src/app/pages/event-info/event-info.component.scss
app/mikane/src/app/pages/event-info/event-info.component.ts
app/mikane/src/app/pages/event-info/event-info.guard.ts
app/mikane/src/app/pages/event-info/event-info.routes.ts
app/mikane/src/app/pages/events/event/event.component.html
app/mikane/src/app/pages/events/event/event.component.ts
app/mikane/src/app/pages/events/events.routes.ts
app/mikane/src/app/pages/participant/participant.component.html
app/mikane/src/app/pages/participant/participant.component.ts

Implements an event info page for non-admins. Currently this page only displays a list of the event's admins.
Closes #287

feat: Event info page for non-admins

---

.github/workflows/api-staging.yml
server/package-lock.json
server/package.json

Improves the backend build chain to create a complete build, with all needed dependencies included (except environment file). Also includes a github action for deploying backend to staging.

fix: Improve backend build

---

app/mikane/package-lock.json
app/mikane/package.json
app/mikane/src/app/pages/reset-password/reset-password.component.spec.ts
app/mikane/src/app/services/auth/auth.service.spec.ts
app/mikane/src/app/services/category/category.service.spec.ts
app/mikane/src/app/services/category/category.service.ts
app/mikane/src/app/services/event/event.service.spec.ts
app/mikane/src/app/services/expense/expense.service.spec.ts
app/mikane/src/app/services/form-validation/form-validation.service.spec.ts
app/mikane/src/app/services/message/message.service.spec.ts
app/mikane/src/app/shared/forms/form-control.pipe.spec.ts

Added tests for
- ResetPasswordComponent
- AuthService
- CategoryService
- EventService
- ExpenseService
- FormValidationService
- MessageService
- FormControlPipe

test: add frontend tests

---

app/mikane/.eslintrc.json
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.scss
app/mikane/src/app/pages/expenditures/expenditures.component.ts
app/mikane/src/app/pages/payment-structure/payment-structure.component.html
app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
app/mikane/src/app/services/message/success/success-message.component.ts

Adds filtering for payers and categories on the expenses page.
Closes #302

feat: Filtering for payers and categories on expenses page

---

.github/workflows/snapshot.yml
app/mikane/src/app/features/mobile/category-item/category-item.component.html
app/mikane/src/app/features/mobile/category-item/category-item.component.ts
app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
app/mikane/src/app/features/split-button/split-button.component.html
app/mikane/src/app/pages/category/category-dialog/category-dialog.component.html
app/mikane/src/app/pages/category/category.component.html
app/mikane/src/app/pages/event-info/event-info.component.html
app/mikane/src/app/pages/event-settings/event-settings.component.html
app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
app/mikane/src/app/pages/expenditures/expenditures.component.html
app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.html
app/mikane/src/app/pages/guests/guests.component.html
app/mikane/src/app/pages/invite/invite.component.html
app/mikane/src/app/pages/participant/participant.component.html
app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.html
app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.html
app/mikane/src/app/pages/payment-structure/payment-structure.component.html
app/mikane/src/app/services/message/success/success-message.component.ts

Changed template iterators to track by id to improve performance
Also fixed issue with split button component and material v3

track by id

---

app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.html
app/mikane/src/app/pages/login/login.component.html
app/mikane/src/app/services/auth/auth.interceptor.ts
server/docker-compose.yml

Handle new error code for trying to access private event, for when a user is removed while still viewing said event
Also a couple other small fixes
Closes #374

feat: navigate to event list if trying to access private event

---

app/mikane/src/app/pages/expenditures/expenditures.component.ts

Payer ID was not sent when editing expense

fix: can't edit expense

---

app/mikane/src/app/pages/expenditures/expense/expense.component.ts

Payer ID was not properly sent when editing expense in mobile view.

fix: Can't edit expense in mobile view

---

app/mikane/src/app/pages/event-settings/event-settings.component.html
app/mikane/src/app/pages/event-settings/event-settings.component.scss
app/mikane/src/app/pages/event-settings/event-settings.component.spec.ts
app/mikane/src/app/pages/event-settings/event-settings.component.ts
app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
app/mikane/src/app/services/event/event.service.spec.ts
app/mikane/src/app/services/event/event.service.ts
server/src/api/notifications.ts
server/src/email-services/notifications/addExpensesReminder.ts
server/src/types/errorCodes.ts
server/tests/notifications.test.ts

Changelog:
- Implemented 'add expenses reminder' email notification
- Moved notifications to separate subsection in event-settings tab (desktop view)
- Added new tests (frontend and backend)
Closes #394

feat: Implement 'add expenses reminder' email
