- app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
Not using proper method for patching form value caused icon to reset when weighted checkbox was used
Fixes #173
> set icon form control properly

- server/src/api.json
- server/src/db/dbEvents.ts
- server/src/email-services/sendEmail.ts
- server/src/parsers/parseEvents.ts
- server/src/types/types.ts
Adds the number of expenses to the user balance object when returned via the GET events/:id/balances endpoint. This can be used in frontend to show the number of expenses in the event per user on the participants page.
Closes #193
> Number of expenses per user

- server/bash_scripts/custom-entrypoint.sh
- server/bash_scripts/db_init.sh
- server/bash_scripts/db_run_functions.sh
- server/docker-compose.yml
When the postgres database container starts, even if a database data directory already exists, all functions will now still run.
> Run postgres functions upon container start

- app/mikane/src/app/pages/category/category.component.html
- app/mikane/src/app/pages/category/category.component.scss
- app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
- app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.scss
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/pages/participant/participant.component.scss
- app/mikane/src/app/pages/participant/participant.component.ts
- app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.html
- app/mikane/src/app/pages/participant/user-dialog/participant-dialog.component.scss
- app/mikane/src/app/pages/payment-structure/payment-structure.component.html
- app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
- app/mikane/src/styles.scss
- server/db_scripts/get_categories.sql
- server/db_scripts/remove_user_from_event.sql
- server/src/api/events.ts
- server/src/db/dbEvents.ts
- server/src/errorHandler.ts
- server/src/parsers/parseCategories.ts
- server/src/types/errorCodes.ts
- server/src/types/types.ts
- server/src/types/typesDB.ts
Changelog (frontend):
- Show user avatars in these additional locations:
- Participants page
- 'Add users to event' dropdown
- User list for a category
- 'Choose participants' dropdown for a category
- Payments page
- 'Add expense' payer dropdown
- Add number of expenses to participants page also in full view
- Disable 'remove user' button in the participants page, if the user has one or more expenses in the event
- Ligten text color of selected value in dropdowns, as it was too dark
Changelog (backend):
- Do not allow users to be removed from an event if they have one or more expenses in it
- Return users' avatar URL when retrieving categories
- Sort the event payments array so that the logged in user is first in the list
Closes #222, closes #223
> feat: Show user avatars, and more

- server/db_scripts/edit_category.sql
- server/db_scripts/edit_expense.sql
- server/src/api.json
- server/src/api/categories.ts
- server/src/api/expenses.ts
- server/src/api/validation.ts
- server/src/db/dbCategories.ts
- server/src/db/dbExpenses.ts
- server/src/types/errorCodes.ts
- server/tests/categories.test.ts
- server/tests/expenses.test.ts
- server/tests/validation.test.ts
Changelog:
- Add endpoint for editing expense. Supports following data:
- name
- description
- categoryID
- amount
- payer
- Add endpoint for editing category. Supports following data:
- name
- icon
- Change validator endpoints from GET to POST
- Fix some API documentation bugs
Closes #2, closes #10
> feat: Endpoints for editing expense/category

- server/src/api.json
- server/src/api/validation.ts
- server/src/db/dbValidation.ts
- server/tests/validation.test.ts
Now all validation endpoints take in an optional resource ID in the body, so it can validate with information about the current resource. This allows the validation endpoints to be used for editing.
Closes #231
> fix: Validation endpoints for editing

- app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
- app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
- app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.html
- app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.scss
- app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.ts
- app/mikane/src/app/pages/payment-structure/payment-structure.component.html
- app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
- app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
Split the payments list into 2 separate lists, one for the user's own payments (both as sender and receiver), and another for other payments. The list of user's payments will start expanded, while the latter list will start collapsed. 
Closes #250
> feat: Split payments into separate lists

- app/mikane/src/app/pages/events/events.component.html
- app/mikane/src/app/pages/events/events.component.scss
- app/mikane/src/app/pages/events/events.component.ts
- app/mikane/src/app/services/event/event.service.ts
Split the events in the events page into 2 sections - one for active events, and one for archived events
Closes #255
> feat: Split events into active and archived sections

- app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
- app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
- app/mikane/src/app/pages/event-settings/event-settings.component.html
- app/mikane/src/app/pages/event-settings/event-settings.component.scss
- app/mikane/src/app/pages/event-settings/event-settings.component.ts
- app/mikane/src/app/pages/event-settings/event-settings.guard.ts
- app/mikane/src/app/pages/event-settings/event-settings.routes.ts
- app/mikane/src/app/pages/events/event/event.component.html
- app/mikane/src/app/pages/events/event/event.component.scss
- app/mikane/src/app/pages/events/event/event.component.ts
- app/mikane/src/app/pages/events/events.component.html
- app/mikane/src/app/pages/events/events.component.ts
- app/mikane/src/app/pages/events/events.routes.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.ts
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/pages/participant/participant.component.scss
- app/mikane/src/app/pages/participant/participant.component.ts
- app/mikane/src/app/services/event/event.service.ts
Implement event settings page.
Changelog:
- Add event settings page with the following features:
- Edit event name and description
- Archive/set active event
- Add and remove event admins
- Delete event
- The event setting page is accesible only for admins, via a navigation tab in full view, and a cog icon in the header on the participants page in mobile view
- Archived tag by the event name in full view
- On the participants page, darken the color of the number of expenses if it is 0
Closes #88
> feat: Event settings page

- app/mikane/src/app/pages/account/danger-zone/danger-zone.component.html
- app/mikane/src/app/pages/event-settings/event-settings.component.html
- server/db_scripts/delete_event.sql
- server/db_scripts/delete_user.sql
- server/db_scripts/delete_user_from_event.sql
- server/db_scripts/get_user.sql
- server/db_scripts/schema/db_schema.sql
- server/src/api/expenses.ts
- server/src/api/users.ts
- server/src/db/dbEvents.ts
- server/src/db/dbUsers.ts
- server/src/types/errorCodes.ts
- server/tests/events.test.ts
- server/tests/users.test.ts
When a user account is deleted the user will now be removed from all active events, while their anonymized data will still be retained in archived events.
Other changes:
- Update frontend account page to accomodate for this account deletion change
- Fix bug where expenses with amount zero were not allowed
- Add better constraints on certain foreign keys in the database
- Prevent archived events from being deleted (this means an event will need to be set active before deletion)
- Fix bug with getting user by username
- Add tests related to event archival and user deletion
Closes #265
> feat: User deletion improvements

- app/mikane/src/app/features/mobile/category-item/category-item.component.html
- app/mikane/src/app/features/mobile/category-item/category-item.component.scss
- app/mikane/src/app/pages/category/category-dialog/category-dialog.component.html
- app/mikane/src/app/pages/category/category-dialog/category-dialog.component.ts
- app/mikane/src/app/pages/event-settings/event-settings.component.ts
- app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.html
- app/mikane/src/app/pages/expenditures/expenditure-dialog/expenditure-dialog.component.ts
Changelog:
- Fix bug where edit expense dialog had wrong title
- Fix bug where edit category dialog appeared as new category if category had no set icon
- Fix bug where guests would be loaded as potential admins
- Fix height of the user list in a category for archived events, when in mobile view
Closes #267, closes #268
> fix: Edit category and expense issues

- app/mikane/src/app/features/mobile/expense-item/expense-item.component.html
- app/mikane/src/app/features/mobile/expense-item/expense-item.component.scss
- app/mikane/src/app/features/mobile/expense-item/expense-item.component.ts
- app/mikane/src/app/pages/events/event/event.component.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.html
- app/mikane/src/app/pages/expenditures/expenditures.routes.ts
- app/mikane/src/app/pages/expenditures/expense/expense.component.html
- app/mikane/src/app/pages/expenditures/expense/expense.component.scss
- app/mikane/src/app/pages/expenditures/expense/expense.component.ts
- app/mikane/src/app/services/expense/expense.service.ts
Adds an expense page, primarily for mobile use, where users can see more details about an expense, as well as edit/delete the expense if they are the payer or an event admin. This page can be accessed by clicking on an expense while in mobile view. In full view, the page is accessible via URL and technically works, but there is no button that will ever take a user there.
Also improves the method of getting the active link in event. Now it correctly gets the ./expenses link even if there is a UUID following it. However, there is an issue remaining where the navbar's active link is not set correctly upon entering the expense page, though it works again after a refresh.
Closes #257, closes #252
> feat: Expense page (mobile)

- app/mikane/src/app/features/mobile/category-item/category-item.component.html
- app/mikane/src/app/pages/category/category.component.html
- app/mikane/src/app/pages/category/category.component.scss
- app/mikane/src/app/pages/expenditures/expenditures.component.html
- app/mikane/src/app/pages/expenditures/expenditures.component.scss
- app/mikane/src/app/pages/payment-structure/payment-structure.component.html
- app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
Add the "no expenses"/"no categories"/"no payments" message for mobile view when an event does not have any of the particular resource. Also swaps trash can icon with minus icon for removing users from a category.
Closes #250
> feat: No resource message on mobile

- app/mikane/src/app/pages/expenditures/expenditures.component.html
- app/mikane/src/app/pages/expenditures/expenditures.component.scss
- app/mikane/src/app/pages/expenditures/expenditures.component.spec.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.ts
- app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.html
- app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.scss
- app/mikane/src/app/pages/expenditures/expense-bottom-sheet/expense-bottom-sheet.component.ts
- app/mikane/src/styles.scss
Implement filtering for mobile view. On the expenses page there are now 3 chip buttons for filtering, each opening a bottom sheet where the user can search through the expenses, and/or filter by payer and category. Similar to full view filtering, active filters will be saved in the URL and the page can therefore be reloaded without losing the filter values.
Closes #304
> feat: Filtering for mobile

- app/mikane/src/app/features/mobile/expense-item/expense-item.component.spec.ts
- app/mikane/src/app/features/mobile/expense-item/expense-item.component.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.html
- app/mikane/src/app/pages/expenditures/expense/expense.component.ts
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/pages/participant/participant.component.spec.ts
- app/mikane/src/app/pages/participant/participant.component.ts
Changelog:
- When someone clicks on a user in the participants page, if the user has one or more expenses in the event, they will be taken to the expenses page filtered by that specific user
- When clicking on an expense and then clicking "go back" any active filters will be maintained on the expenses page
- Fix bug where filter icon for a category did not show if the category has no set icon
Closes #305
> feat: Go to participant expenses (mobile)

- app/mikane/.eslintrc.json
- app/mikane/src/app/features/mobile/event-item/event-item.component.html
- app/mikane/src/app/features/mobile/event-item/event-item.component.scss
- app/mikane/src/app/features/mobile/event-item/event-item.component.ts
- app/mikane/src/app/pages/event-settings/event-settings.component.html
- app/mikane/src/app/pages/event-settings/event-settings.component.scss
- app/mikane/src/app/pages/event-settings/event-settings.component.spec.ts
- app/mikane/src/app/pages/event-settings/event-settings.component.ts
- app/mikane/src/app/pages/events/event/event.component.html
- app/mikane/src/app/pages/events/event/event.component.scss
- app/mikane/src/app/pages/events/events.component.html
- app/mikane/src/app/pages/events/events.component.scss
- app/mikane/src/app/pages/events/events.component.ts
- app/mikane/src/app/pages/login/login.component.scss
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/pages/participant/participant.component.scss
- app/mikane/src/app/pages/participant/participant.component.ts
- app/mikane/src/app/services/event/event.service.spec.ts
- app/mikane/src/app/services/event/event.service.ts
- server/db_scripts/edit_event.sql
- server/src/db/dbEvents.ts
- server/src/types/errorCodes.ts
- server/tests/categories.test.ts
- server/tests/events.test.ts
- server/tests/expenses.test.ts
Add a 'ready to settle' status for events. When an event is in this status, participants can no longer edit the event and will be urged to settle their payments.
Features:
- The event settings page has been updated to allow setting the new event statuses. The flow is as follows:
- Active <-> Ready to settle -> Archived -> Active
- Events with the 'ready to settle' status will show up in the active events list, but will be identifiable as ready for settlement
- Currently this identifier is a different background color and the text READY TO SETTLE instead of the event's description
- On the participants page, if an event is set as ready to settle, there is now an info box above the table informing users the event is ready to be settled (which can be clicked to go directly to the payments …
> feat: Event "ready to settle" status

- .github/workflows/backend-deploy-release.yml
- .github/workflows/backend-test.yml
- .github/workflows/backend.yml
- server/Dockerfile
- server/package-lock.json
- server/package.json
- server/src/server.ts
- server/tests/authentication.test.ts
- server/tests/categories.test.ts
- server/tests/events.test.ts
- server/tests/expenses.test.ts
- server/tests/guestUsers.test.ts
- server/tests/resetDatabase.ts
- server/tests/setup.ts
- server/tests/users.test.ts
- server/tests/validation.test.ts
- server/vitest.config.ts
Updated and refactord backend testing code. After migration to postgres the testing code was unnecessarily complex, so it is now simplified. Also moves backend over to node 20.
Changelog: 
- Removed superfluous code for backend testing
- Upgraded backend to use node 20
- Updated vitest to v1 and refactored accordingly
- Updated various other packages
> chore: Update backend testing

- app/mikane/src/app/pages/guests/guest-dialog/guest-dialog.component.html
- app/mikane/src/app/pages/guests/guests.component.html
- app/mikane/src/app/pages/guests/guests.component.ts
- app/mikane/src/app/services/user/user.service.ts
- server/db_scripts/convert_guest_to_user.sql
- server/db_scripts/delete_guest_user.sql
- server/db_scripts/delete_user.sql
- server/db_scripts/edit_guest_user.sql
- server/db_scripts/edit_user.sql
- server/db_scripts/get_user.sql
- server/db_scripts/get_users.sql
- server/db_scripts/new_guest_user.sql
- server/db_scripts/new_user.sql
- server/db_scripts/schema/2.1-2.2_migrations.sql
- server/db_scripts/schema/db_schema.sql
- server/src/api.json
- server/src/api/authentication.ts
- server/src/api/guestUsers.ts
- server/src/db/dbGuestUsers.ts
- server/src/parsers/parseUsers.ts
- server/src/types/errorCodes.ts
- server/src/types/express-session.d.ts
- server/src/types/types.ts
- server/src/types/typesDB.ts
- server/tests/guestUsers.test.ts
Implements super-admin role for users. This admin role is meant for administrating global application wide systems not related to any specific event.
Now guests can only be deleted/edited by super-admins, with both backend and frontend updated accordingly. For ease of use, note that the creator of a guest will still have delete/edit privileges for that specific guest.
Closes #317, closes #318
> feat: Super-admins - restrictions on managing guests

- app/mikane/src/app/features/mobile/event-item/event-item.component.scss
- app/mikane/src/app/features/mobile/participant-item/participant-item.component.html
- app/mikane/src/app/features/mobile/participant-item/participant-item.component.scss
- app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
- app/mikane/src/app/pages/events/events.component.scss
- app/mikane/src/app/pages/expenditures/expenditures.component.ts
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/services/message/success/success-message.component.ts
Added a 'remove user from event' button when in mobile view. 
Additional change 1:
Slighly adjusted color of 'ready to settle' events in events list.
Additional change 2:
Not sure if itentional or a bug, but there has been change in how setting a signal and notifying its dependants works. This PR therefore also adjusts the way of setting the payer/category filter signal for mobile, to accommodate for this change in behavior.
Additional change 3:
Re-added selector for success-message component (to fix console warning).
Closes #294
> Mobile: 'Remove user from event' button

- app/mikane/src/app/features/mobile/category-item/category-item.component.html
- app/mikane/src/app/features/mobile/category-item/category-item.component.scss
- app/mikane/src/app/features/mobile/category-item/category-item.component.spec.ts
- app/mikane/src/app/features/mobile/category-item/category-item.component.ts
- app/mikane/src/app/pages/category/category.component.html
- app/mikane/src/app/pages/category/category.component.scss
- app/mikane/src/app/pages/category/category.component.spec.ts
- app/mikane/src/app/pages/category/category.component.ts
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/services/category/category.service.ts
- server/db_scripts/add_user_to_category.sql
- server/db_scripts/delete_category.sql
- server/db_scripts/edit_category.sql
- server/db_scripts/edit_category_weighted_status.sql
- server/db_scripts/edit_user_weight.sql
- server/db_scripts/get_categories.sql
- server/db_scripts/new_category.sql
- server/db_scripts/remove_user_from_category.sql
- server/package-lock.json
- server/package.json
- server/src/db/dbCategories.ts
- server/src/parsers/parseCategories.ts
- server/src/types/errorCodes.ts
- server/src/types/types.ts
- server/src/types/typesDB.ts
- server/tests/categories.test.ts
Added information about associated expenses when on the categories page. In full view, there is now a count of linked expenses next to the count of participants in said category. Inside the category dropdown there is also now a "see expenses" button that takes the user to the expenses page, filtered for the given category.
On mobile, there is instead an "expense-icon" button next to the category name, with a number above it counting the number of expenses. Clicking on this button also takes the user to the expenses page, filtered for the given category.
Previously it was too easy to accidently delete a bunch of expenses by deleting their associated category. Now only categories without any expenses can be deleted, meaning any existing expenses need to either change category or be deleted …
> feat: Expenses info on category + prevent deletion of categories with expenses

- app/mikane/src/app/pages/category/category.component.html
- app/mikane/src/app/pages/category/category.component.scss
- app/mikane/src/app/pages/category/category.component.ts
- app/mikane/src/app/pages/events/events.component.html
- app/mikane/src/app/pages/events/events.component.scss
- app/mikane/src/app/pages/events/events.component.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.html
- app/mikane/src/app/pages/expenditures/expenditures.component.scss
- app/mikane/src/app/pages/expenditures/expenditures.component.ts
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/pages/participant/participant.component.scss
- app/mikane/src/app/pages/participant/participant.component.spec.ts
- app/mikane/src/app/pages/participant/participant.component.ts
- app/mikane/src/app/services/scroll/scroll.service.spec.ts
- app/mikane/src/app/services/scroll/scroll.service.ts
Implements a scroll service listening on scroll and resize events (resize required for proper functionality on mobile). On mobile, when the page is scrolled to the bottom, the "new event", "add user to event", "new expense", and "new category" buttons will be hidden so the user can view the content underneath them.
Closes #253
> feat: Scroll service, hide buttons when page is at bottom

- app/mikane/src/app/features/mobile/event-item/event-item.component.html
- app/mikane/src/app/pages/event-settings/event-settings.component.html
- app/mikane/src/app/pages/event-settings/event-settings.component.scss
Disable edit event inputs when event is not active, and fix bug where the 'ready to settle' subtext in the events list would not show for mobile.
Fixes #333, fixes #334
> fix: Disable edit event inputs for non-active events + fix hidden 'ready to settle' text for mobile

- app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
- app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.spec.ts
- app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.ts
- app/mikane/src/app/pages/events/events.component.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.ts
Updates the mobile navbar to use signal input for the "links" object, which fixes the small issue where the wrong navbar text would be displayed when switching between full view and mobile view without refreshing.
Additional change: Somewhat simplifies the overall signal syntax.
Fixes #342
> fix: Update mobile navbar to use signal input

- server/db_scripts/convert_guest_to_user.sql
- server/db_scripts/edit_guest_user.sql
- server/db_scripts/edit_user.sql
- server/db_scripts/edit_user_preferences.sql
- server/db_scripts/get_user.sql
- server/db_scripts/get_users.sql
- server/db_scripts/new_guest_user.sql
- server/db_scripts/new_user.sql
- server/db_scripts/schema/2.2-2.3_migrations.sql
- server/db_scripts/schema/db_schema.sql
- server/package-lock.json
- server/package.json
- server/src/api.json
- server/src/api/users.ts
- server/src/api/validation.ts
- server/src/db/dbUsers.ts
- server/src/parsers/parseUsers.ts
- server/src/types/errorCodes.ts
- server/src/types/types.ts
- server/src/types/typesDB.ts
- server/tests/resetDatabase.ts
- server/tests/users.test.ts
- server/tests/validation.test.ts
There is now a new database table containing user preferences (currently email and phone visibility settings). Furthermore, a new endpoint for setting a user's preferences has been introduced. This endpoint allows changing a user's email and phone visibility settings. The API documentation has been updated to include this new endpoint. Tests have been updated to test the new endpoint.
Make note that the row per user in the database table is mandatory, and will break if the table is not populated after this PR is merged. For new users, the default preferences will be private email and public phone number.
Additional change:
Extended username validation was missing from the edit user endpoint, along with the endpoint specifically for validating a username. These issues have both been fixed …
> feat: Backend support for user preferences

- server/src/api.json
- server/src/api/events.ts
- server/src/api/users.ts
- server/src/parsers/parseUserInfo.ts
In all endpoints that return user data, the email and phone properties are now selectively included on a per user basis based on that user's preferences. For the signed in user however, all data will still be returned.
Fixes #347
> fix: Remove sensitive user information from responses including user data

- server/src/api/users.ts
- server/src/types/errorCodes.ts
- server/tests/users.test.ts
This pull request restricts the ability to edit user data to only the signed-in user. Previously, there were no checks in the backend to ensure that only the user themselves could make changes to their own data.
This also goes for deleting the user. While this action is already protected by a secret key, as an additional security measure the user must now also be signed in to delete their own account.
Tests have been expanded to test for the changes specifically.
Fixes #351
> fix: Restrict editing/deleting user data to signed-in user

- app/mikane/src/app/features/mobile/mobile-event-navbar/mobile-event-navbar.component.html
- app/mikane/src/app/pages/account/account.component.html
- app/mikane/src/app/pages/account/account.component.ts
- app/mikane/src/app/pages/account/preferences/preferences.component.html
- app/mikane/src/app/pages/account/preferences/preferences.component.scss
- app/mikane/src/app/pages/account/preferences/preferences.component.spec.ts
- app/mikane/src/app/pages/account/preferences/preferences.component.ts
- app/mikane/src/app/pages/account/user/user-settings.component.html
- app/mikane/src/app/pages/account/user/user-settings.component.ts
- app/mikane/src/app/pages/event-info/event-info.component.html
- app/mikane/src/app/pages/events/event/event.component.html
- app/mikane/src/app/pages/events/events.component.html
- app/mikane/src/app/services/user/user.service.ts
- app/mikane/src/styles.scss
The account page has been adjusted to include a new preferences section, where the user can change the email and phone number visibility (works in both full view and mobile view). The buttons are using Material's button toggle, and will send a API call simply by clicking one of the buttons. A loading icon will be displayed by the button toggle while the request is being handled, and a checkmark will show by the button toggle when the preference has successfully been saved.
Additional change 1:
In the account details section, clicking cancel after modifying any details would not reset their values to the original values. This has now been corrected.
Additional change 2:
In the account details section, the "save changes" button is now disabled if any of the account details are invalid, …
> feat: Preferences on account page

- app/mikane/src/app/features/mobile/category-item/category-item.component.html
- app/mikane/src/app/features/mobile/category-item/category-item.component.ts
- app/mikane/src/app/features/mobile/participant-item/participant-item.component.html
- app/mikane/src/app/features/mobile/participant-item/participant-item.component.ts
- app/mikane/src/app/features/mobile/payment-item/payment-item.component.html
- app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
- app/mikane/src/app/pages/account/user/user-settings.component.html
- app/mikane/src/app/pages/account/user/user-settings.component.ts
- app/mikane/src/app/pages/category/category.component.html
- app/mikane/src/app/pages/category/category.component.scss
- app/mikane/src/app/pages/category/category.component.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.html
- app/mikane/src/app/pages/expenditures/expenditures.component.scss
- app/mikane/src/app/pages/expenditures/expenditures.component.ts
- app/mikane/src/app/pages/expenditures/expense/expense.component.html
- app/mikane/src/app/pages/expenditures/expense/expense.component.scss
- app/mikane/src/app/pages/expenditures/expense/expense.component.ts
- app/mikane/src/app/pages/participant/participant.component.html
- app/mikane/src/app/pages/participant/participant.component.scss
- app/mikane/src/app/pages/participant/participant.component.ts
- app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.html
- app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.scss
- app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.ts
- app/mikane/src/app/pages/payment-structure/payment-structure.component.html
- app/mikane/src/app/pages/profile/profile.component.html
- app/mikane/src/app/services/category/category.service.ts
- server/src/api.json
- server/src/parsers/parseCategories.ts
- server/src/types/types.ts
Adds clickable user elements to various pages, so it is possible to see any user's profile page by clicking on a user. The following pages have been adjusted:
- Participants page:
- Full view: User avatars are clickable, with a brightness hover effect
- Mobile view: User avatars are clickable
- Expenses page:
- Full view: Payer object is clickable as a whole, with a "box" appearing around the user to show it's clickable when hovered
- Mobile view: The user needs to click into the expense page first, from where the user can click on the user (both avatar and name)
- Categories page:
- Full view: User avatars are clickable, with a brightness hover effect
- Mobile view: User avatars are clickable
- Payments page:
- Full view: User avatars are clickable (both senders and receivers), with a …
> feat: Navigate to user profiles

- app/mikane/src/app/features/menu/menu.component.spec.ts
- app/mikane/src/app/features/menu/menu.component.ts
- app/mikane/src/app/features/mobile/event-item/event-item.component.html
- app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
- app/mikane/src/app/pages/category/category.component.ts
- app/mikane/src/app/pages/events/event-dialog/event-dialog.component.html
- app/mikane/src/app/pages/events/event-dialog/event-dialog.component.scss
- app/mikane/src/app/pages/events/event-dialog/event-dialog.component.ts
- app/mikane/src/app/pages/events/events.component.html
- app/mikane/src/app/pages/events/events.component.ts
- app/mikane/src/app/pages/expenditures/expenditures.component.ts
- app/mikane/src/app/pages/expenditures/expense/expense.component.ts
- app/mikane/src/app/pages/participant/participant.component.ts
- app/mikane/src/app/pages/payment-structure/payment-expansion-panel-item/payment-expansion-panel-item.component.ts
- app/mikane/src/app/pages/profile/profile.component.ts
- app/mikane/src/app/pages/profile/profile.routes.ts
- app/mikane/src/app/services/event/event.service.spec.ts
- app/mikane/src/app/services/event/event.service.ts
- app/mikane/src/app/services/user/user.service.spec.ts
- app/mikane/src/app/services/user/user.service.ts
- server/db_scripts/get_user.sql
- server/src/api.json
- server/src/api/users.ts
- server/tests/users.test.ts
Added a new endpoint for getting a user by their username. The profile page has been updated to use the user's username in the URL instead of the user ID.
Additional change 1:
A toggle for setting the event private when creating a new event was missing from the "private events" PR. This has now been implemented.
Additional change 2:
Added back missing tooltip and styling for private event icon.
Fixes #260
> feat: Get user by username

- app/mikane/src/app/pages/expenditures/expenditures.component.html
- app/mikane/src/app/pages/expenditures/expenditures.component.scss
The edit and delete icons in an expense row will now remain on the same line when the rows shrinks horizontally.
> fix: Prevent line breaks in the expense edit/delete column

- app/mikane/src/app/features/mobile/payment-item/payment-item.component.spec.ts
- app/mikane/src/app/features/mobile/payment-item/payment-item.component.ts
- app/mikane/src/app/pages/payment-structure/payment-structure.component.html
- app/mikane/src/app/pages/payment-structure/payment-structure.component.scss
- app/mikane/src/app/pages/payment-structure/payment-structure.component.spec.ts
- app/mikane/src/app/pages/payment-structure/payment-structure.component.ts
- app/mikane/src/app/pages/reset-password/reset-password.component.scss
- app/mikane/src/app/services/event/event.service.ts
- app/mikane/src/manifest.webmanifest
- server/package-lock.json
- server/package.json
Changelog:
- Added expand/collapse buttons to mobile payments page, one for own payments and one for others' payments
- Refactored payment structure and item components to use signals and computed properties for better state management
- Fixed bug with sending ready-to-settle API call
- Fixed title styling in reset password page
- Added icons property to webmanifest
- Updated relevant tests
Closes #396
> feat: Add expand/collapse buttons to mobile payments page
